### ISSUE TITLE
Incorrect statement about triple negation in section 6.2 

### ISSUE THREAD

**Issue by ghost** [nameiwillforget/hegel-in-mathematics#2]
The clause

> Furthermore, since it is provable in intuitionistic logic that ¬¬¬p is equivalent to ¬¬p

in sentence 5 of the final paragraph of page 15 should instead be 

> Furthermore, since it is provable in intuitionistic logic that ¬¬¬p is equivalent to ¬p

**Comment by nameiwillforget** [comment]
> The clause
> 
> > Furthermore, since it is provable in intuitionistic logic that ¬¬¬p is equivalent to ¬¬p
> 
> in sentence 5 of the final paragraph of page 15 should instead be
> 
> > Furthermore, since it is provable in intuitionistic logic that ¬¬¬p is equivalent to ¬p

Thanks!
